name: flutter_application
description: Una nueva aplicación Flutter.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Icono.png"
  adaptive_icon_background: "assets/icon_background.png" 
  adaptive_icon_foreground: "assets/icon_foreground.png"  

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png