// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxSr5DHcApGMl0a9aH6FDLKtgR1ge_2nE',
    appId: '1:1028152924899:web:a1362e8bb5f609e761c3d6',
    messagingSenderId: '1028152924899',
    projectId: 'kickup-d41b9',
    authDomain: 'kickup-d41b9.firebaseapp.com',
    storageBucket: 'kickup-d41b9.firebasestorage.app',
    measurementId: 'G-B04TZFE8Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD14pZvAr-OnNmjGKCinFyzmyRt6z1vKfI',
    appId: '1:1028152924899:android:4d3d04c99de6cc4d61c3d6',
    messagingSenderId: '1028152924899',
    projectId: 'kickup-d41b9',
    storageBucket: 'kickup-d41b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgrhvfCGzLgqrK2G0f3Tmp5SMuXZq8fEE',
    appId: '1:1028152924899:ios:477a29f9d781566e61c3d6',
    messagingSenderId: '1028152924899',
    projectId: 'kickup-d41b9',
    storageBucket: 'kickup-d41b9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgrhvfCGzLgqrK2G0f3Tmp5SMuXZq8fEE',
    appId: '1:1028152924899:ios:477a29f9d781566e61c3d6',
    messagingSenderId: '1028152924899',
    projectId: 'kickup-d41b9',
    storageBucket: 'kickup-d41b9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxSr5DHcApGMl0a9aH6FDLKtgR1ge_2nE',
    appId: '1:1028152924899:web:43cc92aa830ac2c761c3d6',
    messagingSenderId: '1028152924899',
    projectId: 'kickup-d41b9',
    authDomain: 'kickup-d41b9.firebaseapp.com',
    storageBucket: 'kickup-d41b9.firebasestorage.app',
    measurementId: 'G-E04S7E0KM2',
  );
}
